from settings import *
import textwrap
import cairosvg
import base64
from io import BytesIO
from PIL import Image

class CardHandler:
    def __init__(self):
        self.width = 800
        self.height = 500
        self.profile_color = "#FF5700"

    def get_card(self, username="Crank", content="This Post was generated by Crank!", pfp_path=None, profile_color=None):
        if profile_color is None:
            profile_color = self.profile_color

        svg_content = self._generate_svg(username, content, profile_color, pfp_path)
        temp_dir = tempfile.gettempdir()
        temp_file_path = os.path.join(temp_dir, "card.png")

        png_data = cairosvg.svg2png(bytestring=svg_content.encode('utf-8'))

        image = Image.open(BytesIO(png_data))
        image.save(temp_file_path, format='PNG')
        return temp_file_path

    def _generate_svg(self, username, content, profile_color, pfp_path=None):
        content = content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        wrapped_lines = textwrap.wrap(content, width=30)
        text_elements = ""
        y_position = 220

        for line in wrapped_lines:
            text_elements += f'<text x="40" y="{y_position}" font-family="Arial, sans-serif" font-size="48" font-weight="700" fill="#1c1c1c">{line}</text>\n'
            y_position += 60

        if pfp_path:
            with open(pfp_path, "rb") as img_file:
                img_data = base64.b64encode(img_file.read()).decode('utf-8')
                profile_pic = f'<image x="40" y="70" width="100" height="100" href="data:image/png;base64,{img_data}" />'
        else:
            profile_pic = f'''
            <circle cx="90" cy="120" r="50" fill="{profile_color}"/>
            <circle cx="90" cy="120" r="50" fill="{profile_color}" opacity="0.8"/>
            '''

        svg_template = f'''<svg width="{self.width}" height="{self.height}" viewBox="0 0 {self.width} {self.height}" xmlns="http://www.w3.org/2000/svg">
            <rect x="0" y="0" width="{self.width}" height="{self.height}" rx="20" ry="20" fill="#ffffff" stroke="#e6e6e6" stroke-width="2"/>
            {profile_pic}
            <text x="160" y="135" font-family="Arial, sans-serif" font-size="36" font-weight="700" fill="#1c1c1c">{username}</text>
            {text_elements}
        </svg>'''
        return svg_template
